# Copyright 2016 Mobvoi Inc. All Rights Reserved.
#db.class:"com.mysql.jdbc.Driver"
#db.url:"jdbc:mysql://localhost/vwmobvoi_account?characterEncoding=utf8&amp;zeroDateTimeBehavior=convertToNull&statementInterceptors=com.github.kristofa.brave.mysql.MySQLStatementInterceptor&autoReconnect=true&failOverReadOnly=false"
#db.user:"root"
#db.password:"root"
#db.initialPoolSize:"5"
#db.minPoolSize:"1"
#db.maxPoolSize:"15"
#db.testConnectionOnCheckout:"true"
#

example.property: "I AM IN THE DEFAULT"
#spring.jpa.database: "POSTGRESQL"
spring.datasource.platform:  "postgres"
#spring.jpa.show-sql: "true"
spring.database.driverClassName: "com.mysql.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://localhost/vwmobvoi_account?characterEncoding=utf8&amp;zeroDateTimeBehavior=convertToNull&statementInterceptors=com.github.kristofa.brave.mysql.MySQLStatementInterceptor&autoReconnect=true&failOverReadOnly=false"
spring.datasource.username: "root"
spring.datasource.password: "root"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
#spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
#redis.server: "redis"
#redis.port: "6379"
#signing.key: "345345fsdfsf5345"

# flyway config
#flyway.database=vwmobvoi_account
#flyway.schema.table=schema_version_ma
#flyway.encoding=utf-8
#flyway.locations=classpath:/db/migration
#flyway.setBaselineOnMigrate=true
#flyway.setValidateOnMigrate=false